In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

In [2]:
pd.set_option("display.max_columns", None)
sns.set_theme(style = "darkgrid")
warnings.filterwarnings("ignore")

In [3]:
x = pd.read_csv("../data/cleaned_and_split/x.csv")
x_train = pd.read_csv("../data/cleaned_and_split/x_train.csv")
x_test = pd.read_csv("../data/cleaned_and_split/x_test.csv")
y = pd.read_csv("../data/cleaned_and_split/y.csv")
y_train = pd.read_csv("../data/cleaned_and_split/y_train.csv")
y_test = pd.read_csv("../data/cleaned_and_split/y_test.csv")

In [4]:
x.head()

   Unnamed: 0     x     y    z
0           0  0.04  0.02  1.0
1           1  0.04  0.02  1.0
2           2  0.04  0.02  1.0
3           3  0.04  0.02  1.0
4           4  0.04  0.02  1.0

In [5]:
x_train.head()

   Unnamed: 0     x     y    z
0        9318  0.04  0.03  1.0
1       18896  0.04  0.05  1.0
2        8871  0.04  0.02  1.0
3       18790  0.04  0.04  1.0
4       17362  0.04  0.03  1.0

In [6]:
x_test.head()

   Unnamed: 0     x     y     z
0       10178 -0.14  0.06  0.93
1        8585  0.05  0.02  1.03
2         451 -0.01  0.05  1.12
3        6014  0.04  0.03  1.00
4       15342  0.06 -0.05  1.00

In [7]:
y.head()

   Unnamed: 0  gesture_name
0           0             0
1           1             0
2           2             0
3           3             0
4           4             0

In [8]:
y_train.head()

   Unnamed: 0  gesture_name
0        9318             3
1       18896             6
2        8871             3
3       18790             6
4       17362             6

In [9]:
y_test.head()

   Unnamed: 0  gesture_name
0       10178             3
1        8585             3
2         451             0
3        6014             2
4       15342             5

In [10]:
x.drop(columns = ["Unnamed: 0"], inplace = True)
x_train.drop(columns = ["Unnamed: 0"], inplace = True)
x_test.drop(columns = ["Unnamed: 0"], inplace = True)
y.drop(columns = ["Unnamed: 0"], inplace = True)
y_train.drop(columns = ["Unnamed: 0"], inplace = True)
y_test.drop(columns = ["Unnamed: 0"], inplace = True)

In [11]:
x.head()

      x     y    z
0  0.04  0.02  1.0
1  0.04  0.02  1.0
2  0.04  0.02  1.0
3  0.04  0.02  1.0
4  0.04  0.02  1.0

In [12]:
x_train.head()

      x     y    z
0  0.04  0.03  1.0
1  0.04  0.05  1.0
2  0.04  0.02  1.0
3  0.04  0.04  1.0
4  0.04  0.03  1.0

In [13]:
x_test.head()

      x     y     z
0 -0.14  0.06  0.93
1  0.05  0.02  1.03
2 -0.01  0.05  1.12
3  0.04  0.03  1.00
4  0.06 -0.05  1.00

In [14]:
y.head()

   gesture_name
0             0
1             0
2             0
3             0
4             0

In [15]:
y_train.head()

   gesture_name
0             3
1             6
2             3
3             6
4             6

In [16]:
y_test.head()

   gesture_name
0             3
1             3
2             0
3             2
4             5

In [17]:
x.shape, x_train.shape, x_test.shape, y.shape, y_train.shape, y_test.shape

((18008, 3), (14406, 3), (3602, 3), (18008, 1), (14406, 1), (3602, 1))

In [18]:
# using Sequential API from keras to build a classifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
model = Sequential(
    [
        Dense(64, activation = "relu", input_shape = (3, )), # hidden layer
        Dense(6, activation = "softmax") # output layer
    ]
)

2025-05-07 13:23:38.564208: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2025-05-07 13:23:38.564235: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2025-05-07 13:23:38.564239: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1746604418.564253 22087183 pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
I0000 00:00:1746604418.564279 22087183 pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)

In [20]:
model.weights

[<Variable path=sequential/dense/kernel, shape=(3, 64), dtype=float32, value=[[-1.91315413e-01  1.67502135e-01 -2.13230848e-01 -1.82201266e-02
    1.18082851e-01 -6.54585510e-02  1.39796793e-01  7.45285153e-02
   -1.93488598e-02 -4.36981022e-02  2.07238257e-01  2.54844427e-01
    1.93271548e-01 -8.35917890e-02  2.65250504e-02 -2.74434388e-02
    2.14289427e-01  1.59545481e-01  2.19533443e-01  2.34274328e-01
    1.38870209e-01 -1.07364684e-01 -1.26173794e-01 -7.30828792e-02
    6.82331920e-02 -2.18495294e-01 -9.58353281e-03  2.88102567e-01
   -5.93910962e-02  1.87249541e-01  1.91933572e-01 -6.10885918e-02
    2.98613489e-01  8.15027356e-02  1.68191582e-01 -8.24767649e-02
   -1.41592547e-01  2.08057821e-01  2.75539637e-01 -5.78796715e-02
   -1.86577663e-01  2.77768910e-01  1.09927267e-01  4.68415022e-02
   -2.23987401e-02 -1.93323925e-01 -2.21690029e-01 -1.23831093e-01
   -2.09962934e-01  1.84026927e-01  1.84267521e-01  2.24656880e-01
    7.75876045e-02 -2.79185832e-01  2.11186886e-01 -2.24821955e-01
    4.12087142e-02  2.40782022e-01  2.03145444e-01 -6.93608969e-02
   -6.75517470e-02  9.68318880e-02 -5.86204082e-02  7.74865150e-02]
  [ 3.93500328e-02  1.98311031e-01  2.97311902e-01  4.27783430e-02
    2.53041923e-01 -2.45448053e-02  3.66309881e-02 -2.02530384e-01
   -2.66913384e-01  1.64551586e-01  2.90080011e-01  6.77891076e-02
    1.25701427e-02 -1.73933402e-01  2.08547115e-02 -2.78085232e-01
    7.05181658e-02 -2.36938387e-01  4.88684177e-02 -6.92555904e-02
    2.56003737e-01  7.90335536e-02  8.61618817e-02 -1.66646406e-01
    3.63543630e-03 -1.52715027e-01  1.75461680e-01  1.02714330e-01
   -1.41397551e-01 -1.24509975e-01 -1.56910196e-01  2.44157195e-01
   -2.68428296e-01 -6.75485283e-02 -2.02955604e-02 -9.69386101e-02
    3.82580757e-02 -3.83925438e-02 -2.40407795e-01 -6.69524968e-02
   -2.56243020e-01  1.34387881e-01 -2.58657485e-01 -7.54819363e-02
    1.93301797e-01 -1.97519302e-01  2.59881914e-01  4.15959656e-02
   -9.92466956e-02 -1.10391453e-01 -1.33263305e-01  4.25520241e-02
    2.38655806e-01  2.85341203e-01  2.36746132e-01 -2.64772177e-01
   -1.70508578e-01 -2.21326932e-01  1.58310235e-01  1.84314549e-02
    4.90836203e-02 -2.39927560e-01  2.00569630e-04 -1.12269312e-01]
  [-2.05655992e-02  1.40687287e-01 -2.64362931e-01 -1.82924032e-01
    1.04184359e-01 -2.54525959e-01  3.57593894e-02 -2.68826276e-01
    1.60872906e-01  1.16742253e-02 -1.96160913e-01 -2.56101102e-01
   -2.65307546e-01  6.48068786e-02 -3.35763097e-02 -1.95834711e-01
   -2.96671540e-01  2.73788393e-01  2.17380226e-01  3.16793323e-02
   -7.64183104e-02 -1.71824232e-01 -2.59319305e-01  4.56450880e-02
   -2.71618515e-01 -4.69419658e-02  1.54045165e-01  1.96912050e-01
   -1.42074347e-01  2.40349531e-01 -6.59108162e-03  5.24607599e-02
   -2.59661674e-03  8.06693137e-02 -8.82964432e-02 -2.92601377e-01
   -1.36778012e-01 -1.39464527e-01 -6.75839931e-02 -1.76497281e-01
   -1.91260993e-01 -1.30952358e-01  1.06617808e-01 -1.91670507e-01
    2.92627156e-01 -1.59453943e-01  1.72651649e-01  2.74836004e-01
   -1.24762818e-01 -2.60118961e-01 -7.55760521e-02 -2.11939812e-02
    1.40529394e-01 -1.27918378e-01 -8.55793804e-02 -1.95592552e-01
    1.71502173e-01 -2.44528115e-01  2.52596378e-01  1.53888494e-01
   -1.31320655e-02 -9.81139243e-02 -7.42042065e-03 -1.01473734e-01]]>,
 <Variable path=sequential/dense/bias, shape=(64,), dtype=float32, value=[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]>,
 <Variable path=sequential/dense_1/kernel, shape=(64, 6), dtype=float32, value=[[ 0.0246667  -0.2871167  -0.20946561  0.17768276 -0.21195468  0.19668859]
  [ 0.08159372 -0.10308255  0.16834626 -0.22957572 -0.06384318 -0.14981285]
  [-0.20575634 -0.28333595  0.02811122 -0.16020347  0.14621678 -0.23714434]
  [ 0.0750826   0.01843229  0.25196284 -0.28940573 -0.27385926 -0.13827355]
  [ 0.194927   -0.16621676 -0.27744392  0.04853284  0.20653924 -0.27037096]
  [ 0.20099077 -0.20578349 -0.07333274 -0.1421643  -0.03384438 -0.09251142]
  [ 0.2197876   0.11430228 -0.01468763 -0.16732033 -0.2366484  -0.11992195]
  [-0.12232754  0.03709149 -0.2744068   0.19531935 -0.28096786 -0.23549722]
  [ 0.17690521  0.00615582  0.08902264 -0.01272571  0.14763194  0.01894617]
  [ 0.27551877 -0.09348494  0.28247404  0.02725592  0.18582463 -0.01694313]
  [-0.16715741 -0.20421827  0.25488013 -0.12617801  0.08779651 -0.18351957]
  [-0.22567569 -0.2168135  -0.03694192  0.25377876 -0.1642861   0.17542821]
  [ 0.07713106  0.17058036  0.20389578  0.0471651  -0.17535976  0.250408  ]
  [ 0.00361413 -0.2613766   0.1550678  -0.17547792  0.23657864 -0.2763509 ]
  [-0.2532786   0.08269554 -0.29261115  0.19161394 -0.04319496 -0.28056887]
  [ 0.16836149 -0.2570313   0.03854758 -0.06067836 -0.21770383  0.21607429]
  [ 0.08553934  0.24674541  0.09435627 -0.16060595 -0.10688438 -0.11437906]
  [-0.1918371   0.18700549  0.11566532 -0.17552322  0.06550643  0.1717771 ]
  [-0.28900617 -0.29125538  0.1366275  -0.07022189  0.08629262 -0.03567132]
  [-0.08330868 -0.2217753   0.07825795 -0.18322676  0.12735361 -0.26055607]
  [ 0.20849782 -0.02337131 -0.1560763  -0.1795073   0.18759552  0.02199119]
  [ 0.24200004 -0.13505723  0.2609061   0.25744057  0.0828248  -0.25010458]
  [ 0.15190431 -0.07357739  0.00322074 -0.2227006   0.2557392  -0.09333648]
  [-0.13693294  0.28259122 -0.03263345 -0.19521026  0.14692667 -0.16385138]
  [-0.14270513  0.28935343 -0.19753718 -0.12777382  0.2664823  -0.28997084]
  [ 0.22198582  0.06119511 -0.03553638 -0.23829348  0.01990753  0.2457779 ]
  [ 0.16232231  0.00076014  0.27265972 -0.12744464 -0.02485663 -0.05334128]
  [-0.1535002   0.20699883 -0.25334483  0.08676791  0.21485424 -0.19023955]
  [-0.18899128  0.11545143 -0.24131778  0.06024587 -0.20638469  0.09188321]
  [-0.2591275  -0.08155756 -0.21460867 -0.00768638  0.15724668 -0.09116808]
  [ 0.24468547 -0.05817856  0.20725566 -0.06587553 -0.2568191  -0.2754247 ]
  [ 0.01437506 -0.26061743 -0.06650557 -0.20235895 -0.02341619  0.19240919]
  [-0.1877546   0.23537374  0.02349144 -0.27503937  0.20915753 -0.1886628 ]
  [ 0.24018395  0.00728348 -0.03145403 -0.15504253 -0.0454594  -0.11273181]
  [ 0.22669035 -0.28735843  0.2918936  -0.06385316 -0.17532994 -0.07671268]
  [ 0.09250772  0.07507032 -0.04574455  0.12308055 -0.11574565  0.10617763]
  [ 0.11517474  0.14127105  0.12145871 -0.14449807 -0.27983457  0.21615165]
  [-0.0416289   0.21950763 -0.06039239  0.09047768  0.15977892 -0.24750328]
  [ 0.11787885 -0.1913956   0.24495101 -0.11450548  0.06607795  0.03570899]
  [-0.0919687   0.04001227  0.25351596  0.13069063 -0.06887639 -0.16930172]
  [-0.05415574  0.18962452  0.10234043 -0.18184957 -0.03336263  0.05123466]
  [-0.03970635  0.12283605 -0.05028285  0.04196653 -0.18453415 -0.28856426]
  [-0.19081485 -0.04458618  0.13186052  0.11112422 -0.1828531   0.22507334]
  [ 0.00482011  0.08674642  0.2924024   0.14509618  0.1887143   0.20659593]
  [-0.21936749  0.11137858  0.08143163 -0.15157945  0.06519544  0.25993288]
  [-0.16302688  0.0676859  -0.11757892 -0.13389845 -0.10341683 -0.10964888]
  [-0.11655395  0.11712304  0.08002079  0.14712477 -0.12172487 -0.01156938]
  [-0.14759329  0.12036178 -0.2368617   0.06209624 -0.00666419 -0.27715528]
  [ 0.23377681  0.02805516  0.23467475 -0.01098931  0.12059465 -0.09562744]
  [ 0.21641457 -0.00689733 -0.09148079 -0.21430658  0.2627864   0.15146127]
  [ 0.00889674  0.2303192   0.21308059 -0.16994807  0.12530869 -0.29048374]
  [-0.21226537  0.27523237 -0.06880707 -0.0593508  -0.2763981  -0.06405587]
  [ 0.06774211  0.21553749 -0.23698387  0.2639532  -0.04605307 -0.07744099]
  [ 0.07626671 -0.06198959 -0.28121057 -0.17665045  0.2311179   0.04250163]
  [-0.10023093  0.10452759  0.2578177  -0.16170456  0.14519992 -0.14766644]
  [ 0.23931235  0.1931417  -0.19617954  0.0298788  -0.00283194 -0.25211215]
  [-0.25582924 -0.23944598 -0.17789969  0.17230019  0.17497095 -0.18478927]
  [-0.18837771 -0.23945059 -0.09142844 -0.11814536 -0.19177324 -0.25441357]
  [-0.21490555 -0.2899279   0.16069251  0.07914674 -0.1953091  -0.19349915]
  [-0.1566641  -0.05203383 -0.04285783 -0.08327398 -0.09473579  0.16767317]
  [-0.11188813 -0.2606057  -0.2613845  -0.16612281  0.12129539  0.20019439]
  [-0.25367907 -0.20996909 -0.06523301 -0.06841987  0.08631775  0.00489023]
  [-0.04237759 -0.27984288 -0.12518564 -0.16724871  0.24491233 -0.2517685 ]
  [-0.26992363 -0.00463331 -0.20692426  0.28882957  0.27444237  0.077885  ]]>,
 <Variable path=sequential/dense_1/bias, shape=(6,), dtype=float32, value=[0. 0. 0. 0. 0. 0.]>]

In [21]:
len(model.weights) # w1, b1, w2, b2

4

In [22]:
for i in model.weights:
    print(i.shape)

(3, 64)
(64,)
(64, 6)
(6,)